### ISSUE TITLE
Color picker adds random characters when you try to input a hex value

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#29]
![screen shot 2017-05-22 at 6 46 50 pm](https://cloud.githubusercontent.com/assets/15987931/26331473/0a1f5ac6-3f1f-11e7-9c27-55eb14b255a9.png)

To recreate: 

1. Select an color input field
2. Click into the hex value input
3. Start typing the desired hex value. 

You'll see it jumps to a random hex value before you can enter your 6 characters.

**Comment by mirshko** [comment]
This is a bug with the color-picker package. Seems its filed with them as well. 

https://github.com/xiaokaike/vue-color/issues/65

**Comment by danieljmurphy91** [comment]
Roger that. let's see if they can fix. If not, do we have a backup plan for another package?

**Comment by mirshko** [comment]
I would say going with the system's color picker isn't the worst option, and it works well. Even though it opens a new Window its not the worst UX, especially since a marketer might already be familiar with the color picker.

Additionally they can see their cta changing color as they switch colors anyways. So its not that bad.

**Comment by danieljmurphy91** [comment]
I think it's pretty bad. Consider us. We use #1b5faa for everything. If I can't manually enter that into the field, I can't use the app.

**Comment by mirshko** [comment]
Ahh forgot about that part.

**Comment by danieljmurphy91** [comment]
Can you try another plug-in? Is that a ton of work?

**Comment by mirshko** [comment]
Bug fixed in vue-color version 2.2.0
