### ISSUE TITLE
BETA BLOCKER: button text styling overwritten by HubSpot portal styling? 

### ISSUE THREAD

**Issue by danieljmurphy91** [buildbetterCTAs/app.responsivectabuilder.com#74]
Example embed code: 

<script>function load(e){var t=document.getElementsByTagName("head")[0],n=document.createElement("link");return n.type="text/css",n.rel="stylesheet",n.href=e,t.appendChild(n),n}load('https://unpkg.com/cta.css');</script>
<div class="cta" style="border-radius: 4px; background-image: linear-gradient(rgba(72, 167, 249, 0.5), rgba(72, 167, 249, 0.5)), url('https://unsplash.it/1280/720'); background-color: #0E589A;">
    <div class="ctaHeadline" style="color: #ffffff;">This is a powerful, eye-catching headline</div>
    <div class="ctaDescription" style="color: #ffffff;">This is your secondary text that might explain why your reader should follow your call-to-action.</div>
    <div class="ctaButton hubl" style="background-color: #109BFF; color: #FFFFFF;">
        {{ cta('076d252e-d477-46ea-81b6-8f0b3c7556ff') }}
    </div>
</div>

<br>

Note that the last `<div>` has inline css for white text. However if you load this CTA into the HubSpot Blog and look at the preview, the button text is blue. Somehow the CTA styling is overwriting the inline css.

**Comment by mirshko** [comment]
@danieljmurphy91 photo please?

**Comment by danieljmurphy91** [comment]
Check out this blog preview: https://www.onshape.com/cad-blog/-temporary-slug-346919be-0fee-4c68-87ea-5166b81cb0f8?hs_preview=KtIPAFlH-5194656333

Note the inline css calls for white button text. Note that the button text is blue.

**Comment by danieljmurphy91** [comment]
Actually looks like it's only occurring on the Text Color and Button Text Color input fields.

**Comment by mirshko** [comment]
I see. this bug relates to cta-css package.

**Comment by mirshko** [comment]
<img width="582" alt="screenshot 2017-06-11 11 40 15" src="https://user-images.githubusercontent.com/8116716/27012288-eab09a52-4e9a-11e7-9c87-fd7d59c81349.png">

@danieljmurphy91 Should be fixed. However due to the usage of !important in the blog styles the hover color chosen by the master stylesheets. It could be possible to override this as well though with the usage of !important on the a:hover color declaration in cta.css

**Comment by danieljmurphy91** [comment]
Will that cause a UX hiccup? Does the user have to you the important statement to use the app successfully?

**Comment by mirshko** [comment]
I added a small fix and am waiting to see if it will fix it.

**Comment by mirshko** [comment]
I believe this is a fluke use-case and is due to extreme specificity with the way we declared hover styles on our website blog. I don't think this will be an issue with the average user with more normal selector declarations. If we see this is indeed an issue it might require some rethinking. 

In terms of our website I can make a fix to the declarations to prevent it from happening.

**Comment by danieljmurphy91** [comment]
Okay. That works for me. These types of bugs are why we want to BETA test. Good to know.
