### ISSUE TITLE
Add ability to adjust border radius for CTA button

### ISSUE THREAD

**Issue by mirshko** [buildbetterCTAs/app.responsivectabuilder.com#87]
**User Feedback**: *"Corner radius for both CTA and Button"*

**Proposed Additions**: Add slider for this, same as CTA radius slider.

**Comment by danieljmurphy91** [comment]
I'm torn. In some ways I want to preserve a specific look for the CTA that's universal across all blogs, websites, landing pages, etc (the Responsive CTA Builder look). I think of that as part of the value we provide: we're helping marketers make really sexy CTAs because some marketers can't design for shit. At the same time, radius on the button doesn't feel like a drastic move that would alter the overall feel of the CTA. I'd say let's sit on this too? Reconsider at a later point?
